### ISSUE TITLE
bowtie2-build non-zero exit does not propagate up to midas_run_genes subcommand

### ISSUE THREAD

**Issue by bsmith89** [czbiohub/iggtools#36]
I currently have a problematic installation of Bowtie2, resulting in a bowtie2-build failure

```
$ bowtie2-build --threads 10 data/SS01120.m.proc.iggtools/genes/temp_sc3.0/pangenomes.fa data/SS01120.m.proc.iggtools/genes/temp_sc3.0/pangenomes > data/SS01120.m.proc.iggtools/genes/temp_sc3.0/bowtie2-build.log
/pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/bowtie2-build-s: /pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/../lib/libtbb.so.2)
```

which includes an exit code of `1`.

However, iggtools exit code is still `0`.

```
$ iggtools midas_run_genes --threads 10 --debug -1 data/SS01120.m.proc.r1.fq.gz -2 data/SS01120.m.proc.r2.fq.gz data/SS01120.m.proc.iggtools
1580506602.8:  Doing important work in subcommand midas_run_genes with args
[....debug output removed....]
1580506645.8:  'bowtie2-build --threads 10 data/SS01120.m.proc.iggtools/genes/temp_sc3.0/pangenomes.fa data/SS01120.m.proc.iggtools/genes/temp_sc3.0/pangenomes > data/SS01120.m.proc.iggtools/genes/temp_sc3.0/bowtie2-build.log'
/pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/bowtie2-build-s: /pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /pollard/home/bsmith/anaconda3/envs/ucfmt4/bin/../lib/libtbb.so.2)
$ echo $?
0

```

As a result, pipelines that include this iggtools call _do not fail_, and try to run the next step.

The problem is that the `iggtools.subcommands.midas_run_genes.midas_run_genes` function [catches ALL exceptions](https://github.com/czbiohub/iggtools/blob/c8fd1a834e81c5df6c84f4730a6da7316ad04cda/iggtools/subcommands/midas_run_genes.py#L291) and performs cleanup without a final non-zero exit.

This same (IMO anti-) pattern is also used in midas_run_snps, but doesn't seem to be used in midas_run_species.

The expected behavior is for errors in subcommands to result in iggtools exiting with a non-zero exit code.

**Comment by zhaoc1** [comment]
Thanks Bryton. I added your suggested fix in PR #43
